# Generated by Django 5.1.6 on 2025-02-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, null=True)),
                ('categoryDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('productPrice', models.CharField(max_length=200, null=True)),
                ('productOriginalPrice', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('discription', models.CharField(max_length=500, null=True)),
                ('productDate', models.DateField(auto_now_add=True, null=True)),
                ('categoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImageURL', models.ImageField(blank=True, null=True, upload_to='product_image_detial/')),
                ('productImageDate', models.DateField(auto_now_add=True, null=True)),
                ('productImageId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
