# Generated by Django 5.1.6 on 2025-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_category_categoryproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('heroCaption', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
