# Generated by Django 5.1.6 on 2025-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularProductImage', models.ImageField(blank=True, null=True, upload_to='popular_product/')),
                ('popularProductCaption', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
