# Generated by Django 5.1.6 on 2025-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularLocationImage', models.ImageField(blank=True, null=True, upload_to='popular_location/')),
                ('popularLocationCaption', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
