# Generated by Django 5.1.6 on 2025-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_popularlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceAreaImage', models.ImageField(blank=True, null=True, upload_to='service_area/')),
                ('serviceAreaTile', models.CharField(max_length=200, null=True)),
                ('serviceAreaSubTitle', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
