# Generated by Django 5.1.6 on 2025-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_servicearea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryProduct',
            new_name='ProductType',
        ),
    ]
