# Generated by Django 5.1.6 on 2025-03-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_categoryproduct_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='productTypeId',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='categoryDate',
            new_name='productTypeDate',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='categoryName',
            new_name='productTypeName',
        ),
    ]
