# Generated by Django 5.1.6 on 2025-03-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_categoryid_product_producttypeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='productTypeName',
            new_name='type',
        ),
    ]
