# Generated by Django 5.1.6 on 2025-03-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_productcolor_product_productcolorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceRange', models.CharField(max_length=200, null=True)),
                ('productPriceRangeDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productPriceRangeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productpricerange'),
        ),
    ]
