# Generated by Django 5.1.6 on 2025-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_productpricerange_product_productpricerangeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('SubTitle', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
