# Generated by Django 5.1.6 on 2025-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_footertitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertitle',
            old_name='SubTitle',
            new_name='SubTitle1',
        ),
        migrations.AddField(
            model_name='footertitle',
            name='SubTitle2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footertitle',
            name='SubTitle3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
