# Generated by Django 5.1.6 on 2025-03-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_subtitle_footertitle_subtitle1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertitle',
            name='linkSub1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footertitle',
            name='linkSub2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footertitle',
            name='linkSub3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
