# Generated by Django 5.1.6 on 2025-03-10 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_footertitle_linksub1_footertitle_linksub2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200, null=True)),
                ('menuId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Sub2Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200, null=True)),
                ('menuId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.submenu')),
            ],
        ),
    ]
