# Generated by Django 5.1.6 on 2025-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogItemImage', models.ImageField(blank=True, null=True, upload_to='blog_item_image/')),
                ('dayDate', models.CharField(max_length=200, null=True)),
                ('monthDate', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('subTitle', models.CharField(max_length=200, null=True)),
                ('infoTitle', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
