# Generated by Django 5.1.6 on 2025-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_blogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBodyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseName', models.CharField(max_length=200, null=True)),
                ('houseLocation', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('durationContact', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('emailTitle', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
