# Generated by Django 5.1.6 on 2025-03-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_blogitem_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='blogTitleDetails',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
