# Generated by Django 5.1.6 on 2025-03-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_blogitem_blogtitledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200, null=True)),
                ('blogTitleDetails', models.CharField(max_length=200, null=True)),
                ('blogItemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.blogitem')),
            ],
        ),
    ]
