# Generated by Django 5.1.6 on 2025-03-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_blogitemdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogitem',
            name='blogTitleDetails',
        ),
        migrations.RemoveField(
            model_name='blogitem',
            name='discription',
        ),
    ]
