# Generated by Django 5.1.6 on 2025-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_blogitem_blogtitledetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWelcomeUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomeUsImageURL', models.ImageField(blank=True, null=True, upload_to='contact_welcome_us/')),
            ],
        ),
    ]
